// the Contours lens's parity fixture (plan 2026-09-07 § D31): run the browser's OWN interpolator (src/contour.worker.ts,
// bundled by esbuild with `self` shimmed) over a small deterministic point set and write every cell of the three
// methods' value + error surfaces and their fit lines. calcofi4r::cc_interpolate() and calcofi4py.interpolate()
// reproduce the same numbers from the same algorithm; their tests read this file (tests/testthat/fixtures/contour_fixture.json
// and tests/fixtures/contour_fixture.json are byte-identical copies of it).
//   node scripts/parity/contour_fixture.mjs [out.json]
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
const here = path.dirname(new URL(import.meta.url).pathname), root = path.resolve(here, "../..");
const bundle = path.join(here, ".contour.worker.bundle.mjs");
execSync(`npx esbuild ${path.join(root, "src/contour.worker.ts")} --bundle --format=esm --platform=neutral --outfile=${bundle} --log-level=error`, { cwd: root });
const replies = [];
globalThis.self = { postMessage: (r) => replies.push(r), onmessage: null };
await import(pathToFileURL(bundle).href);
// a seeded LCG so the fixture is reproducible without a dependency; 30 points on a jittered 6 × 5 grid off southern California
let seed = 20260907; const rnd = () => { seed = (seed * 1664525 + 1013904223) % 4294967296; return seed / 4294967296; };
const pts = [];
for (let j = 0; j < 5; j++) for (let i = 0; i < 6; i++) {
  const lon = -122.5 + i * 0.6 + (rnd() - 0.5) * 0.2, lat = 31.5 + j * 0.5 + (rnd() - 0.5) * 0.2;
  const z = 12 + 3 * Math.sin((lon + 122) * 1.3) + 2 * Math.cos((lat - 31) * 2.1) + (rnd() - 0.5) * 0.6;
  pts.push({ lon: +lon.toFixed(6), lat: +lat.toFixed(6), z: +z.toFixed(6) });
}
const params = { cellDeg: 0.25, maskKm: 60 };
const out = { about: "calcofi explorer contour parity fixture — generated by scripts/parity/contour_fixture.mjs from src/contour.worker.ts", generated: new Date().toISOString().slice(0, 10), params, points: pts, methods: {} };
const round = (a) => Array.from(a, (v) => (Number.isFinite(v) ? +v.toFixed(6) : null));
// the global cases (the station grain) and the local ones (nmax nearest per cell — the cast grain; 8 here so the 30 points exercise it)
for (const [key, method, nmax] of [["idw", "idw", 0], ["ok", "ok", 0], ["tps", "tps", 0], ["idw_l8", "idw", 8], ["ok_l8", "ok", 8]]) {
  replies.length = 0;
  self.onmessage({ data: { id: 1, lon: Float64Array.from(pts, (p) => p.lon), lat: Float64Array.from(pts, (p) => p.lat), z: Float64Array.from(pts, (p) => p.z), method, cellDeg: params.cellDeg, maskKm: params.maskKm, wantSe: true, nmax } });
  const v = replies.find((r) => r.kind === "value"), s = replies.find((r) => r.kind === "se");
  if (!v) throw new Error(`no value reply for ${key}: ${JSON.stringify(replies)}`);
  out.grid = out.grid ?? v.grid;
  const se = v.se ?? s?.se ?? null;
  out.methods[key] = { method, nmax, fit: { n: v.fit.n, nCells: v.fit.nCells, loo: +v.fit.loo.toFixed(6), nLoo: v.fit.nLoo ?? null, vg: v.fit.vg ? { nugget: +v.fit.vg.nugget.toFixed(6), psill: +v.fit.vg.psill.toFixed(6), range: +v.fit.vg.range.toFixed(6) } : null, edf: v.fit.edf != null ? +v.fit.edf.toFixed(6) : null }, values: round(v.values), se: se ? round(se) : null };
}
out.dist = round(replies.find((r) => r.kind === "value").dist);
fs.unlinkSync(bundle);
const dest = process.argv[2] ?? path.join(here, "contour_fixture.json");
fs.writeFileSync(dest, JSON.stringify(out));
console.log(`${dest}: ${pts.length} points · grid ${out.grid.nx}×${out.grid.ny} · ` + Object.entries(out.methods).map(([m, r]) => `${m} loo ${r.fit.loo}${r.fit.vg ? ` range ${r.fit.vg.range.toFixed(0)}` : ""}${r.fit.edf != null ? ` edf ${r.fit.edf.toFixed(2)}` : ""}`).join(" · "));
