// the brand icon set (plan D15) from src/icons.tsx's map: a <symbol> sprite for <use href> and a CSS file
// exporting every glyph as a mask custom property (the way theme.css exports --cc-icon-sun / --cc-icon-moon),
// plus a contact sheet to check the set side by side at 16 px. The explorer keeps rendering the paths inline
// (React owns the nodes, no cross-origin <use>); the sprite and the masks are for everyone else — the
// calcofi.io cards, db-viz-station, Quarto and pkgdown pages.
//   node scripts/build_icons.mjs [../CalCOFI.github.io/brand/v1]
import fs from "node:fs";
import path from "node:path";

const out = process.argv[2] ?? path.resolve("../CalCOFI.github.io/brand/v1");
// Node ≥ 23 strips the types of a .ts import; the module imports nothing but @mdi/js
const { ICON } = await import(path.resolve("src/icon-paths.ts"));
const names = Object.keys(ICON).filter((k) => !k.startsWith("ui-") || ["ui-help", "ui-about", "ui-feedback", "ui-download", "ui-expand", "ui-collapse", "ui-left", "ui-right", "ui-up", "ui-down", "ui-close", "ui-sql", "ui-share", "ui-search", "ui-minimize", "ui-more", "ui-link", "ui-image", "ui-code", "ui-data", "ui-layers", "ui-filter", "ui-years", "ui-tune", "ui-github", "ui-open", "ui-check"].includes(k));
const esc = (d) => d.replace(/"/g, "'");
const sprite = `<!-- calcofi.io brand v1 — icons (Material Design Icons, Pictogrammers, Apache-2.0, plus bespoke marine glyphs drawn to the same
     24-px grid and weight). GENERATED by CalCOFI/explore scripts/build_icons.mjs from src/icons.tsx — do not hand-edit.
     Usage (same-origin): <svg class="cc-icon"><use href="/brand/v1/icons/calcofi-icons.svg#cat-fish"/></svg>; cross-origin pages
     use icons.css (masks) instead. Ids: cat-* categories · lens-* the explorer's lenses · realm-* · ui-* actions. -->
<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
${names.map((n) => `  <symbol id="${n}" viewBox="0 0 24 24"><path d="${esc(ICON[n])}"/></symbol>`).join("\n")}
</svg>
`;
const url = (d) => `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cpath d='${esc(d)}'/%3E%3C/svg%3E")`;
const css = `/* calcofi.io brand — icons.css (v1)
   Every glyph of brand/v1/icons/calcofi-icons.svg as a mask custom property, the way theme.css exports
   --cc-icon-sun / --cc-icon-moon: <i class="cc-i cc-i-cat-fish"></i> draws it in the text colour with CSS alone,
   on any page (cross-origin included). GENERATED by CalCOFI/explore scripts/build_icons.mjs — do not hand-edit.
   Material Design Icons (Pictogrammers, Apache-2.0) + bespoke marine glyphs on the same 24-px grid. Additive in v1. */
:root {
${names.map((n) => `  --cc-icon-${n}: ${url(ICON[n])};`).join("\n")}
}
.cc-i { display: inline-block; width: 1em; height: 1em; vertical-align: -0.15em; background-color: currentColor;
  -webkit-mask: var(--cc-i) no-repeat center / contain; mask: var(--cc-i) no-repeat center / contain; }
${names.map((n) => `.cc-i-${n} { --cc-i: var(--cc-icon-${n}); }`).join("\n")}
`;
fs.mkdirSync(path.join(out, "icons"), { recursive: true });
fs.writeFileSync(path.join(out, "icons", "calcofi-icons.svg"), sprite);
fs.writeFileSync(path.join(out, "icons.css"), css);
// the contact sheet: every glyph at 16, 24 and 40 px in both themes, for the eye
const sheet = `<!doctype html><meta charset="utf-8"><title>calcofi.io icons</title><link rel="stylesheet" href="../theme.css"><link rel="stylesheet" href="../icons.css">
<style>body{font-family:var(--sans);padding:16px;background:var(--bg);color:var(--fg)} .g{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:8px} .c{display:flex;align-items:center;gap:8px;padding:6px;border:1px solid var(--border);border-radius:6px;font-size:11px} .c span{color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis} .l{display:inline-block;width:50%;padding:12px 0} .light{background:#fff;color:#212529}</style>
<h3>calcofi.io brand v1 — icons (${names.length})</h3><div class="g">${names.map((n) => `<div class="c"><i class="cc-i cc-i-${n}" style="font-size:16px"></i><i class="cc-i cc-i-${n}" style="font-size:24px"></i><i class="cc-i cc-i-${n}" style="font-size:40px"></i><span>${n}</span></div>`).join("")}</div>`;
fs.writeFileSync(path.join(out, "icons", "index.html"), sheet);
console.log(`wrote ${names.length} icons → ${path.join(out, "icons/calcofi-icons.svg")} (${(sprite.length / 1e3).toFixed(1)} KB), ${path.join(out, "icons.css")} (${(css.length / 1e3).toFixed(1)} KB), icons/index.html`);
