# the bundled registry snapshot src/spatial_layers.fallback.ts (plan 2026-08-31, D23) — the layers the app draws when a
# release has no spatial_layers.json sidecar. built by the SAME calcofi4db::build_spatial_layers() release_database.qmd
# runs, from a published release's spatial + sample_spatial tables (read over HTTPS by their catalog paths, never a
# local copy) and the registry CSV in ~/Github/CalCOFI/workflows, which must be on main.
#   Rscript scripts/dev_spatial_layers.R            # the release latest.txt names
#   Rscript scripts/dev_spatial_layers.R v2026.10.08
suppressPackageStartupMessages({ devtools::load_all("~/Github/CalCOFI/calcofi4db", quiet = TRUE); library(DBI); library(glue) })
base     <- "https://storage.googleapis.com/calcofi-db/"; prefix <- "ducklake/releases"
wf       <- path.expand("~/Github/CalCOFI/workflows")
version  <- commandArgs(TRUE)[1]
if (is.na(version)) version <- trimws(readLines(glue("{base}{prefix}/latest.txt"), warn = FALSE))
wf_branch <- system2("git", c("-C", wf, "branch", "--show-current"), stdout = TRUE)
if (wf_branch != "main") warning(glue("{wf} is on `{wf_branch}`, not main: the registry CSV may not be the merged one"))

# a table's object URLs from the release catalog (port of src/release.ts sources(): canonical objects, then compat_path)
cat_json <- jsonlite::fromJSON(glue("{base}{prefix}/{version}/catalog.json"), simplifyVector = FALSE)
urls <- function(table) {
  t <- Filter(function(x) x$name == table, cat_json$tables)[[1]]
  p <- if (length(t$objects)) vapply(t$objects, function(o) o$path, "") else t$compat_path
  paste0(base, p) }
con <- get_duckdb_con(":memory:"); load_duckdb_extension(con, "spatial"); load_duckdb_extension(con, "httpfs")
for (tbl in c("spatial", "sample_spatial"))
  dbExecute(con, glue("CREATE TABLE {tbl} AS SELECT * FROM read_parquet([{paste(shQuote(urls(tbl)), collapse = ',')}])"))

x <- build_spatial_layers(
  con, file.path(wf, "metadata/spatial_layers.csv"), version,
  pmtiles_base   = "https://storage.googleapis.com/calcofi-files-public/_spatial/",
  built          = format(file.mtime(file.path(wf, "data/parquet/spatial/manifest.json")), "%Y-%m-%d"),
  reference_json = file.path(wf, "data/parquet/spatial/reference_layers.json")) # the reference rows' counts (D52)
writeLines(c(
  "// GENERATED by scripts/dev_spatial_layers.R (the bundled registry snapshot for a release without the",
  "// spatial_layers.json sidecar, D23) — regenerate there, do not edit.",
  paste0("export default ", jsonlite::toJSON(x, auto_unbox = TRUE, digits = NA, null = "null", pretty = TRUE), ";")),
  "src/spatial_layers.fallback.ts")
cat(glue("wrote src/spatial_layers.fallback.ts ({version}): {length(x$layers)} layers · ",
         "{sum(vapply(x$layers, function(l) l$n_features, 1L))} features · ",
         "{sum(vapply(x$layers, function(l) l$n_memberships, 1L) > 0)} with memberships\n"))
