# spatial_layers.json for the explore-dev catalog + the bundled fallback (plan 2026-08-31, D23) —
# built by the SAME calcofi4db::build_spatial_layers() release_database.qmd runs, from the local
# v2026.08.25 release's spatial table + the dev catalog's sample_spatial, so the app is written
# against the true shape and the next release changes nothing for it.
#   Rscript scripts/dev_spatial_layers.R
suppressPackageStartupMessages({ devtools::load_all("~/Github/CalCOFI/calcofi4db", quiet = TRUE); library(DBI); library(glue) })
rel <- path.expand("~/_big/calcofi/releases/v2026.08.25/parquet"); version <- "v2026.08.25"
dev <- path.expand("~/_big/calcofi/explore-spike/data2/explore-dev/releases/v2026.08.25")
con <- get_duckdb_con(":memory:"); load_duckdb_extension(con, "spatial")
dbExecute(con, glue("CREATE TABLE spatial AS SELECT * FROM '{rel}/spatial.parquet'"))
ss <- Sys.glob(path.expand("~/_big/calcofi/explore-spike/data2/explore-dev/tables/sample_spatial/*/*.parquet"))
dbExecute(con, glue("CREATE TABLE sample_spatial AS SELECT * FROM read_parquet({paste0('[', paste(shQuote(ss), collapse = ','), ']')})"))
x <- build_spatial_layers(
  con, "~/Github/CalCOFI/workflows/metadata/spatial_layers.csv", version,
  pmtiles_base = "https://storage.googleapis.com/calcofi-files-public/_spatial/",
  built = format(file.mtime(path.expand("~/Github/CalCOFI/workflows/data/parquet/spatial/manifest.json")), "%Y-%m-%d"))
f <- file.path(dev, "spatial_layers.json")
jsonlite::write_json(x, f, auto_unbox = TRUE, digits = NA, null = "null")
cat(glue("wrote {f} ({round(file.size(f) / 1e3)} KB)\n\n"))
writeLines(c(
  "// GENERATED by scripts/dev_spatial_layers.R (the bundled registry snapshot for a release without the",
  "// spatial_layers.json sidecar, D23) — regenerate there, do not edit.",
  paste0("export default ", jsonlite::toJSON(x, auto_unbox = TRUE, digits = NA, null = "null", pretty = TRUE), ";")),
  "src/spatial_layers.fallback.ts")
cat("wrote src/spatial_layers.fallback.ts\n")
cat(glue("{length(x$layers)} layers · {sum(vapply(x$layers, function(l) l$n_features, 1L))} features · ",
         "{sum(vapply(x$layers, function(l) l$n_memberships, 1L) > 0)} with memberships\n"))
system2("gcloud", c("storage", "cp", shQuote(file.path(dev, "spatial_layers.json")),
                    "gs://calcofi-db/explore-dev-root/explore-dev/releases/v2026.08.25/spatial_layers.json"))
cat("uploaded to gs://calcofi-db/explore-dev-root/.../spatial_layers.json\n")
